name: Release

on: workflow_dispatch

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build universal binary
        run: |
          swift build -c release --arch x86_64 --arch arm64